version: 2.1

orbs:
  maven: circleci/maven@1.1

workflows:
  maven_test:
    jobs:
      #- cd spring-autowired-npe/ && maven/test
      - maven/test :
          #https://stackoverflow.com/questions/65602920/circleci-maven-build-fails-missing-pom-xml
          app_src_directory: spring-autowired-npe
      
       
